trigger:
- main

pool: d65

steps:
- script: npm install
  displayName: 'Download Nodejs Dependencies'

- script: docker build -t cart .
  displayName: 'Docker Build'

- script:
    aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 041583668323.dkr.ecr.us-east-1.amazonaws.com
    docker tag cart:latest 041583668323.dkr.ecr.us-east-1.amazonaws.com/cart:latest
    docker push 041583668323.dkr.ecr.us-east-1.amazonaws.com/cart:latest
  displayName: 'Docker Push Image to ECR'